### ISSUE TITLE
How to make the mid section Grid layout height changes

### ISSUE THREAD

**Issue by SunilDevalla** [DsunilK/NYTimes-Clone#1]
Will discuss in the morning call about the placement

**Comment by kimothokamau** [comment]
>

- make the NYT logo, hamburger, and search clickable
- increase line-height for the paragraphs

**Comment by SunilDevalla** [comment]
> > 
> 
> * make the NYT logo, hamburger, and search clickable
> * increase line-height for the paragraphs

Thanks for the Suggestions KK

**Comment by SunilDevalla** [comment]
All fixes Made as suggested
